name: Deploy to EC2

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v2 

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts


    - name: Copy file to EC2 and replace Nginx html
      run: |
        scp index.html ubuntu@${{ secrets.EC2_HOST }}:/tmp/index.html
        ssh ubuntu@${{ secrets.EC2_HOST }} "sudo mv /tmp/index.html /var/www/html/"
